"""Dump table/column/index/relationship metadata from an Access .accdb via ODBC.

Run on Windows with the Access Database Engine (ACE) driver installed:

    python schema_dump.py "R:\\RATS_Competitions_be.accdb"

Writes schema.json (machine-readable) and schema.md (human-readable) into
the current directory.
"""
import json
import sys

import pyodbc

SYSTEM_TABLE_PREFIXES = ("MSys",)


def connect(db_path):
    conn_str = (
        r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};"
        rf"DBQ={db_path};"
    )
    return pyodbc.connect(conn_str, autocommit=True)


def is_user_table(name):
    return not name.startswith(SYSTEM_TABLE_PREFIXES)


def dump_tables(cursor):
    tables = {}
    for row in cursor.tables(tableType="TABLE"):
        name = row.table_name
        if not is_user_table(name):
            continue
        tables[name] = {"columns": [], "primary_key": [], "indexes": [], "foreign_keys": []}

    for table_name in tables:
        columns = []
        for col in cursor.columns(table=table_name):
            columns.append(
                {
                    "name": col.column_name,
                    "type": col.type_name,
                    "size": col.column_size,
                    "nullable": bool(col.nullable),
                    "ordinal_position": col.ordinal_position,
                }
            )
        columns.sort(key=lambda c: c["ordinal_position"])
        tables[table_name]["columns"] = columns

        pk_cols = [row.column_name for row in cursor.primaryKeys(table=table_name)]
        tables[table_name]["primary_key"] = pk_cols

        indexes = {}
        for row in cursor.statistics(table=table_name):
            if row.index_name is None:
                continue
            indexes.setdefault(
                row.index_name,
                {"unique": not bool(row.non_unique), "columns": []},
            )
            if row.column_name:
                indexes[row.index_name]["columns"].append(row.column_name)
        tables[table_name]["indexes"] = [
            {"name": name, **info} for name, info in indexes.items()
        ]

        fks = []
        for row in cursor.foreignKeys(foreignTable=table_name):
            fks.append(
                {
                    "fk_column": row.fkcolumn_name,
                    "references_table": row.pktable_name,
                    "references_column": row.pkcolumn_name,
                    "fk_name": row.fk_name,
                }
            )
        tables[table_name]["foreign_keys"] = fks

    return tables


def dump_views(cursor):
    return sorted(row.table_name for row in cursor.tables(tableType="VIEW"))


def write_markdown(tables, views, path):
    with open(path, "w", encoding="utf-8") as f:
        f.write("# RATS Access database schema\n\n")
        f.write("Auto-generated by schema_dump.py. Review before treating as ground truth.\n\n")
        for name, info in sorted(tables.items()):
            f.write(f"## {name}\n\n")
            if info["primary_key"]:
                f.write(f"Primary key: `{', '.join(info['primary_key'])}`\n\n")
            f.write("| Column | Type | Size | Nullable |\n|---|---|---|---|\n")
            for col in info["columns"]:
                f.write(
                    f"| {col['name']} | {col['type']} | {col['size']} | {col['nullable']} |\n"
                )
            if info["foreign_keys"]:
                f.write("\nForeign keys:\n")
                for fk in info["foreign_keys"]:
                    f.write(
                        f"- `{fk['fk_column']}` -> `{fk['references_table']}.{fk['references_column']}`\n"
                    )
            if info["indexes"]:
                f.write("\nIndexes:\n")
                for idx in info["indexes"]:
                    uniq = "UNIQUE " if idx["unique"] else ""
                    f.write(f"- {uniq}`{idx['name']}` ({', '.join(idx['columns'])})\n")
            f.write("\n")

        if views:
            f.write("## Saved queries (views)\n\n")
            f.write("SQL text for these is in queries.json (see query_sql_dump.py).\n\n")
            for v in views:
                f.write(f"- {v}\n")


def main():
    if len(sys.argv) != 2:
        print("usage: schema_dump.py <path-to.accdb>")
        sys.exit(1)

    db_path = sys.argv[1]
    conn = connect(db_path)
    cursor = conn.cursor()

    tables = dump_tables(cursor)
    views = dump_views(cursor)

    with open("schema.json", "w", encoding="utf-8") as f:
        json.dump({"tables": tables, "views": views}, f, indent=2)

    write_markdown(tables, views, "schema.md")

    print(f"Found {len(tables)} user tables, {len(views)} saved queries.")
    print("Wrote schema.json and schema.md")


if __name__ == "__main__":
    main()
